general:
  bind: 127.0.0.1
  port: 3000
  token: change-this

bitcoin:
  host: 192.155.92.133
  port: 8332
  username: bitcoinrpc
  password: HhaZ4YHzBpx8oarpUS1SbtdR3Ywp6kqS5jGnqYrmSV7v

pricing:
  provider: bitpay